# frozen_string_literal: true
module Stupidedi
  using Refinements

  module Guides
    module FiftyTen
      module X220A1

        b = GuideBuilder
        d = Schema
        r = SegmentReqs
        e = ElementReqs
        s = Versions::FunctionalGroups::FiftyTen::SegmentDefs
        t = Versions::FunctionalGroups::FiftyTen::TransactionSetDefs

        BE834 = b.build(t::BE834,
          d::TableDef.header("Table 1 - Header",
            b::Segment(100, s::ST, "Transaction Set Header",
              r::Required, d::RepeatCount.bounded(1),
              b::Element(e::Required,    "Transaction Set Identifier Code", b::Values("834")),
              b::Element(e::Required,    "Transaction Set Control Number"),
              b::Element(e::NotUsed,     "Implementation Guide Version Name")),
            b::Segment(200, s::BGN, "Beginning Segment",
              r::Required, d::RepeatCount.bounded(1),
              b::Element(e::Required,    "Original Transaction"),
              b::Element(e::Required,    "Transaction ID"),
              b::Element(e::Required,    "Date"),
              b::Element(e::Required,    "Time"),
              b::Element(e::Required,    "Central Time"),
              b::Element(e::Required,    "Blank"),
              b::Element(e::Required,    "Blank"),
              b::Element(e::Required,    "Verify Action Code")),
            b::Segment(300, s::REF, "Reference Information",
              r::Required, d::RepeatCount.bounded(1),
              b::Element(e::Required,     "Master Policy Number"),
              b::Element(e::Required,     "Reference Identification"),
              b::Element(e::NotUsed,     ""),
              b::Element(e::NotUsed,     "")),
            b::Segment(400, s::QTY, "Employee Quantity",
              r::Required, d::RepeatCount.bounded(3),
              b::Element(e::Required,     "Quantity Code"),
              b::Element(e::Required,     "Quantity"),
              b::Element(e::NotUsed,     ""),
              b::Element(e::NotUsed,     "")),
            b::Segment(500, s::N1, "Employee Quantity",
              r::Required, d::RepeatCount.unbounded,
              b::Element(e::Required,     ""),
              b::Element(e::Required,     ""),
              b::Element(e::Required,     ""),
              b::Element(e::Required,     ""),
              b::Element(e::NotUsed,     ""),
              b::Element(e::NotUsed,     "")),
            d::LoopDef.build("1000A Covered",
              d::RepeatCount.unbounded,
              b::Segment(1000, s::INS, "",
                r::Required, d::RepeatCount.bounded(1),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, "")),
              b::Segment(1000, s::REF, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::NotUsed, ""),
                b::Element(e::NotUsed, "")),
              b::Segment(1000, s::DTP, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, "")),
              b::Segment(1000, s::NM1, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, "")),
              b::Segment(1000, s::PER, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, "")),
              b::Segment(1000, s::N3, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, "")),
              b::Segment(1000, s::N4, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, "")),
              b::Segment(1000, s::DMG, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::NotUsed, ""),
                b::Element(e::NotUsed, ""),
                b::Element(e::NotUsed, ""),
                b::Element(e::NotUsed, ""),
                b::Element(e::NotUsed, ""),
                b::Element(e::NotUsed, ""),
                b::Element(e::NotUsed, ""),
                b::Element(e::NotUsed, "")),
              b::Segment(1000, s::HLH, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, "")),
              b::Segment(1000, s::HD, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, "")),
              b::Segment(1000, s::AMT, "",
                r::Required, d::RepeatCount.unbounded,
                b::Element(e::Required, ""),
                b::Element(e::Required, ""),
                b::Element(e::Required, "")),
            )))
      end
    end
  end
end
